Repository jetstack/vault-unsealer, pull requests merged in 2018-09, with the labels that each got.

#19 Add CONTRIBUTING.md
  CONTRIBUTING.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, retest-not-required-docs-only, size/M

#20 Upgrade to golang 1.10.4
  .gitlab-ci.yml
  Makefile
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#21 Creates local mode for unseal key shares in path
  cmd/root.go
  cmd/util.go
  pkg/kv/local/local.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M
