Repository jetstack/vault-unsealer, pull requests merged in 2019-01, with the labels that each got.

#35 Updates Gopkg.toml and removes bad logrus vendor
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/Sirupsen/logrus/.gitignore
  vendor/github.com/Sirupsen/logrus/.travis.yml
  vendor/github.com/Sirupsen/logrus/CHANGELOG.md
  vendor/github.com/Sirupsen/logrus/LICENSE
  vendor/github.com/Sirupsen/logrus/README.md
  vendor/github.com/Sirupsen/logrus/alt_exit.go
  vendor/github.com/Sirupsen/logrus/alt_exit_test.go
  vendor/github.com/Sirupsen/logrus/doc.go
  vendor/github.com/Sirupsen/logrus/entry.go
  vendor/github.com/Sirupsen/logrus/entry_test.go
  vendor/github.com/Sirupsen/logrus/exported.go
  vendor/github.com/Sirupsen/logrus/formatter.go
  vendor/github.com/Sirupsen/logrus/formatter_bench_test.go
  vendor/github.com/Sirupsen/logrus/hook_test.go
  vendor/github.com/Sirupsen/logrus/hooks.go
  vendor/github.com/Sirupsen/logrus/hooks/syslog/README.md
  vendor/github.com/Sirupsen/logrus/hooks/syslog/syslog.go
  vendor/github.com/Sirupsen/logrus/hooks/syslog/syslog_test.go
  vendor/github.com/Sirupsen/logrus/hooks/test/test.go
  vendor/github.com/Sirupsen/logrus/hooks/test/test_test.go
  vendor/github.com/Sirupsen/logrus/json_formatter.go
  vendor/github.com/Sirupsen/logrus/json_formatter_test.go
  vendor/github.com/Sirupsen/logrus/logger.go
  vendor/github.com/Sirupsen/logrus/logger_bench_test.go
  vendor/github.com/Sirupsen/logrus/logrus.go
  vendor/github.com/Sirupsen/logrus/logrus_test.go
  vendor/github.com/Sirupsen/logrus/terminal_bsd.go
  vendor/github.com/Sirupsen/logrus/terminal_linux.go
  vendor/github.com/Sirupsen/logrus/text_formatter.go
  vendor/github.com/Sirupsen/logrus/text_formatter_test.go
  vendor/github.com/Sirupsen/logrus/writer.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#36 Use DOCKER_HOST: tcp://localhost:2375
  .gitlab-ci.yml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#31 Docs: Added documentation on how to retrieve keys from AWS KMS.
  docs/aws-kms-ssm.md
Labels: approved, dco-signoff: yes, lgtm, release-note, retest-not-required-docs-only, size/S

#38 Upgrade alpine image to 3.8
  Dockerfile
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#40 Upgrades go to 1.11.4
  .gitlab-ci.yml
  Makefile
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS
